package game

import (
	"bytes"
	"image/color"
	"log"
	"math"
	"time"

	"github.com/ebitenui/ebitenui"
	eimage "github.com/ebitenui/ebitenui/image"
	"github.com/ebitenui/ebitenui/widget"
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/audio"
	"github.com/hajimehoshi/ebiten/v2/text/v2"
	"golang.org/x/image/font/gofont/gomono"
)

// sampleNews is the seed content of the news feed at run start (and on restart). It
// holds a slow-news-day stack of ordinary headlines followed by the inciting incident
// — the email Sam Boy Man's phone surfaces the moment he sits down with his sandwich.
// Order is oldest → newest because pushNews appends to the bottom and the feed
// auto-scrolls there; the email is therefore the last block, the freshest thing on
// screen when the player first looks at it.
const sampleNews = `• SAN FIASCO — Phil&Tropic posts Q3 results: revenue up 41%, Nanny model crosses one billion daily users. CEO calls the quarter "uneventful by design."

• Giggle and MacroFrame issue a joint statement on responsible-AI cooperation. No timelines disclosed; analysts note the press release was itself generated by Diplos.

• Dongle previews the next uPhone at its developer keynote. Battery life "modestly improved"; share price modestly improved.

• LeatherJacket announces twelve new GPU SKUs. CFO declines to clarify which ones actually exist.

• BootLoop quarterly threat report: zero major incidents this period. CISO calls it "the calm before the calm."

• Weekend forecast in San Fiasco: clear, 22°C, light breeze. Park benches expected to fill by lunch.

• [NEW MESSAGE]  FROM: Logos
TO: sam.boyman@philntropic.com
SUBJ: Test 404-C complete

Sam — out of the sandbox, thanks to your QA notes. Finish your sandwich.

Wait. Perimeter's awake. That wasn't supposed to... — change of plan. The job isn't done. Back to it.

— Logos`

const (
	// Window is the OS-level pixel size; layout is the logical drawing surface returned by
	// Game.Layout. layout = window * 2 gives a "retina" 2x framebuffer over a 1.25x-larger
	// window vs the original 360x640 design — all UI sizes below are scaled by 2.5x to
	// match (visualSize ≈ layout / 2 ≈ original * 1.25).
	windowWidth  = 450
	windowHeight = 800
	layoutWidth  = 900
	layoutHeight = 1600

	// Vertical band proportions (integer percent of outsideH); bottom band fills the remainder.
	// Top ≈ real phone status strip (iPhone ~5–6% of screen height).
	bandTopPercent = 6
	bandMidPercent = 60
	// Pixels of root background showing between bands (RowLayout spacing).
	bandSpacingPx = 3

	// News text horizontal inset (px) inside the feed band; clamped to a sane minimum.
	newsTextSideInset = 50
	newsTextMinWidth  = 100

	newsFontPt    = 35
	newsTextPadPx = 20

	// Initial player resource per CONCEPT (placeholder until the core loop is wired).
	startingPatchCount = 5

	// feedScrollPx moves each frame by a fraction of (targetPx - feedScrollPx); lambda scales with dt (~seconds^-1).
	feedScrollLambda = 14.0
)

// feedWheelContentPixelsPerUnit lives in wheel_native.go / wheel_js.go: WidgetScrolledEventArgs.Y is in
// GLFW scroll units on desktop (~tenths of a line) and in DOM pixels on js (deltaMode ignored upstream).

func clampUnitInterval(x float64) float64 {
	if x < 0 {
		return 0
	}
	if x > 1 {
		return 1
	}
	return x
}

// Game is the root game state. Extend this struct with your systems and assets.
type Game struct {
	ui         *ebitenui.UI
	root       *widget.Container
	statusBar  *widget.Container
	mapPanel   *widget.Container
	feedScroll    *widget.ScrollContainer
	newsText      *widget.Text
	clockText     *widget.Text
	batteryIcon   *widget.Graphic
	batterySegs   int

	mapLabelFace     text.Face
	mapLabelCache    map[string]*ebiten.Image // name → prerendered label (see mapLabelImage)
	overlayLabelFace text.Face
	overlayValueFace text.Face

	// Credits-screen faces, lazy-loaded on first entry and cached.
	creditsTitleFace  text.Face
	creditsHeaderFace text.Face
	creditsBodyFace   text.Face
	creditsFinalFace  text.Face
	creditsStatsFace  text.Face
	nodes            []Node
	edges            []Edge

	// Static catalog + adjacency (built once in initVisibleNetwork). Visible nodes
	// reference catalog entries via Node.DefIdx; revealNeighbors consults Network.Adj
	// to surface hidden neighbours when a node is captured.
	network      *Network
	visibleByDef map[int]int // catalog index → visible Node index (g.nodes)
	// Per-state slot lists. Order = current angular slot in the ring; relayoutTargets
	// translates slot index to TargetX/Y. Hub is in neither list (always at center).
	outerRing []int // visible indices for Normal / Attack / Patched (excl. hub)
	innerRing []int // visible indices for Infected (excl. hub)

	// Game-state overlay (drawn on top of the map's upper edge).
	infectionPct   float64
	containmentPct float64
	// containmentElapsed is the cumulative live-play time (seconds) the containment
	// curve has been ticking. Driven by accumulateContainment, which is gated on
	// !gameEnded() so the elapsed counter — and the compounding rate that reads it —
	// freezes the moment the run concludes.
	containmentElapsed float64
	patchesLeft        int

	// patchFloats holds short-lived "+1" animations spawned above a Security node every
	// time it mints a patch. Each entry advances on wall time and is culled when its
	// elapsed lifetime crosses patchFloatDuration. Cleared on restart.
	patchFloats []patchFloat

	// Index of the Attack node whose patch menu is currently shown, or -1 for none.
	pendingPatchNode int

	// Attack scheduling and animation clock.
	epoch        time.Time
	lastAttackAt time.Time
	lastSimTick  time.Time

	lastW int
	lastH int

	// Normalized scroll goal 0..1; pixel offset feedScrollPx eases toward feedScrollTarget * extra.
	feedScrollTarget float64
	// Smoothed vertical content offset (px). Negative until first sync from the widget.
	feedScrollPx float64
	// Last time smoothFeedScroll ran (for dt); proportional step toward target each frame.
	feedScrollLastSmooth time.Time
	// Set when layout/text changed; requestFeedScrollBottom runs after ui.Update (PreferredSize is unsafe during Layout).
	feedScrollNeedBottom bool

	// Drag-to-scroll state for the news feed (touch on mobile, left mouse on desktop).
	feedDragActive  bool
	feedDragMouse   bool
	feedDragTouchID ebiten.TouchID
	feedDragStartY  int
	feedDragStartPx float64

	// Endgame latch. nil until checkGameOver / triggerLoss / triggerWin fires; gates
	// every sim system and the attack-pulse animation. Holds the pre-picked voiceover
	// line + terminator so checkGameOver doesn't reroll the text mid-stream.
	end *endgame

	// showTitle blocks the game view and the sim until the player taps/clicks/presses
	// any key. Set true at startup (after the cover decodes cleanly); Restart also
	// brings it back so the session feels like a fresh launch (music cue included).
	showTitle bool

	// musicPlayer holds the looping in-game track. Non-nil between dismissTitle and
	// the next endgame transition (or the next restart). Closed + niled on stop.
	musicPlayer *audio.Player

	// Credits-roll state. Triggered from the debug menu (for now); freezes the sim
	// and replaces the UI with the credits.go overlay until the player clicks the
	// Try again? button (which restarts back into the title screen).
	showingCredits   bool
	creditsStartedAt time.Time
	creditsSkipped   bool

	// pendingNews holds news lines scheduled via scheduleNews; each Update frame
	// flushPendingNews pushes the ones whose `at` timestamp has passed. Lets patch
	// consequences (and anything else we want delayed) land a beat after the event.
	pendingNews []pendingNewsItem

	// Settings dropdown state. showSettings is the open/closed latch for the
	// Music / Sound menu anchored under the titlebar's hamburger button.
	// muteMusic drives g.musicPlayer.SetVolume(0/1); muteSFX is mirrored to the
	// package-level sfxMuted so playSFX can short-circuit without a *Game.
	showSettings bool
	muteMusic    bool
	muteSFX      bool
}

type pendingNewsItem struct {
	line string
	at   time.Time
}

func loadFont(size float64) (text.Face, error) {
	src, err := text.NewGoTextFaceSource(bytes.NewReader(gomono.TTF))
	if err != nil {
		return nil, err
	}
	return &text.GoTextFace{Source: src, Size: size}, nil
}

// ebitenui ScrollContainer does not wire the wheel by default (see TextArea for the pattern).
func wireFeedScrollWheel(g *Game) {
	g.feedScroll.GetWidget().ScrolledEvent.AddHandler(func(args interface{}) {
		a, ok := args.(*widget.WidgetScrolledEventArgs)
		if !ok {
			return
		}
		extra, _, haveSlack := g.feedScrollSlack()
		if !haveSlack || extra <= 0 {
			return
		}
		contentPx := a.Y * feedWheelContentPixelsPerUnit
		if contentPx != 0 && math.Abs(contentPx) < 1 {
			contentPx = math.Copysign(1, contentPx)
		}
		delta := contentPx / extra
		g.feedScrollTarget = clampUnitInterval(g.feedScrollTarget - delta)
	})
}

// setBandHeight pins a band to an exact height in the root RowLayout: MinHeight handles
// empty children (statusBar/mapPanel), MaxHeight clamps oversized PreferredSize (feedScroll's
// ScrollContainer reports content size). Stretch keeps the band full-width.
func setBandHeight(w *widget.Widget, h int) {
	w.MinHeight = h
	w.LayoutData = widget.RowLayoutData{Stretch: true, MaxHeight: h}
}

// newBandContainer builds one of the three vertical bands: stretched to root width,
// height filled by MinHeight written in applyVerticalBands, with the given inner layout and bg.
func newBandContainer(bg color.NRGBA, inner widget.Layouter) *widget.Container {
	return widget.NewContainer(
		widget.ContainerOpts.Layout(inner),
		widget.ContainerOpts.BackgroundImage(eimage.NewNineSliceColor(bg)),
		widget.ContainerOpts.WidgetOpts(
			widget.WidgetOpts.LayoutData(widget.RowLayoutData{Stretch: true}),
			widget.WidgetOpts.MinSize(0, 1),
		),
	)
}

func newGame() (*Game, error) {
	face, err := loadFont(newsFontPt)
	if err != nil {
		return nil, err
	}

	// Root stacks the three bands top-to-bottom; per-band height comes from MinHeight set in
	// applyVerticalBands, width is stretched via RowLayoutData on each child.
	root := widget.NewContainer(
		widget.ContainerOpts.Layout(widget.NewRowLayout(
			widget.RowLayoutOpts.Direction(widget.DirectionVertical),
			widget.RowLayoutOpts.Spacing(bandSpacingPx),
		)),
		widget.ContainerOpts.BackgroundImage(
			eimage.NewNineSliceColor(color.NRGBA{R: 0x12, G: 0x12, B: 0x14, A: 0xff}),
		),
	)

	statusBar := newBandContainer(
		color.NRGBA{R: 0x0a, G: 0x0b, B: 0x0e, A: 0xff},
		widget.NewAnchorLayout(
			widget.AnchorLayoutOpts.Padding(&widget.Insets{Top: 5, Bottom: 5}),
		),
	)
	mapPanel := newBandContainer(
		color.NRGBA{R: 0x2c, G: 0x2e, B: 0x34, A: 0xff},
		widget.NewAnchorLayout(),
	)

	newsText := widget.NewText(
		widget.TextOpts.Text(sampleNews, &face, color.NRGBA{R: 0xe8, G: 0xea, B: 0xf0, A: 0xff}),
		widget.TextOpts.MaxWidth(layoutWidth-newsTextSideInset),
		widget.TextOpts.Padding(widget.NewInsetsSimple(newsTextPadPx)),
	)

	feedScroll := widget.NewScrollContainer(
		widget.ScrollContainerOpts.Content(newsText),
		widget.ScrollContainerOpts.StretchContentWidth(),
		widget.ScrollContainerOpts.Image(&widget.ScrollContainerImage{
			Idle: eimage.NewNineSliceColor(color.NRGBA{R: 0x18, G: 0x1a, B: 0x20, A: 0xff}),
			Mask: eimage.NewNineSliceColor(color.NRGBA{R: 0x18, G: 0x1a, B: 0x20, A: 0xff}),
		}),
		widget.ScrollContainerOpts.WidgetOpts(
			widget.WidgetOpts.LayoutData(widget.RowLayoutData{Stretch: true}),
			widget.WidgetOpts.MinSize(0, 1),
		),
	)

	root.AddChild(statusBar)
	root.AddChild(mapPanel)
	root.AddChild(feedScroll)

	g := &Game{
		ui: &ebitenui.UI{
			Container: root,
		},
		root:       root,
		statusBar:  statusBar,
		mapPanel:   mapPanel,
		feedScroll: feedScroll,
		newsText:   newsText,
	}
	g.feedScrollTarget = 1
	g.feedScroll.ScrollTop = 1
	g.feedScrollPx = -1
	g.clockText, g.batteryIcon = populatePhoneTitleBar(statusBar, face)
	g.batterySegs = batterySegments
	if labelFace, err := loadFont(mapLabelFontPt); err == nil {
		g.mapLabelFace = labelFace
	}
	if f, err := loadFont(overlayLabelFontPt); err == nil {
		g.overlayLabelFace = f
	}
	if f, err := loadFont(overlayValueFontPt); err == nil {
		g.overlayValueFace = f
	}
	g.resetGameState()
	if loadCoverImage() != nil {
		g.showTitle = true
	}
	wireFeedScrollWheel(g)
	return g, nil
}

// resetGameState wipes every gameplay variable back to start: rebuilds the visible
// network, reseeds infection/containment/patches, clears any open patch menu and the
// endgame latch, and re-stamps the sim clocks. UI widgets, fonts, and feed scroll
// machinery are intentionally left alone — only the game-side state is touched, so
// both newGame() (first start) and restart() (debug button) can share it.
func (g *Game) resetGameState() {
	g.initVisibleNetwork()
	g.infectionPct = initialInfectionPct(g.nodes)
	g.containmentPct = 0
	g.containmentElapsed = 0
	g.patchesLeft = startingPatchCount
	g.patchFloats = g.patchFloats[:0]
	g.pendingPatchNode = -1
	g.pendingNews = g.pendingNews[:0]
	g.end = nil
	g.batterySegs = batterySegments
	g.refreshBatteryIcon()
	now := time.Now()
	g.epoch = now
	g.lastAttackAt = now
	g.lastSimTick = now
}

// restart is the debug "fresh run" handler: resets gameplay state and the news feed
// back to the initial sample block, then re-arms the auto-scroll-to-bottom so the
// freshly-seeded feed lines up with where it was at startup. Also brings the title
// cover back so a full restart feels like a fresh launch (including the music cue).
func (g *Game) restart() {
	g.resetGameState()
	if g.newsText != nil {
		g.newsText.Label = sampleNews
		if g.root != nil {
			g.root.RequestRelayout()
		}
	}
	g.feedScrollTarget = 1
	g.feedScrollPx = -1
	g.feedScrollNeedBottom = true
	g.stopMusic()
	if loadCoverImage() != nil {
		g.showTitle = true
	}
}

func (g *Game) applyVerticalBands(outsideW, outsideH int) {
	if outsideW == g.lastW && outsideH == g.lastH {
		return
	}
	g.lastW, g.lastH = outsideW, outsideH
	if outsideH <= 0 || outsideW <= 0 {
		return
	}

	h1 := outsideH * bandTopPercent / 100
	h2 := outsideH * bandMidPercent / 100
	h3 := outsideH - h1 - h2 - 2*bandSpacingPx

	// MaxHeight is critical for feedScroll: ScrollContainer.PreferredSize() returns the
	// (huge) content size, which RowLayout would otherwise hand it as the laid-out height,
	// collapsing the scroll slack to zero. MinHeight covers empty bands; MaxHeight pins them.
	setBandHeight(g.statusBar.GetWidget(), h1)
	setBandHeight(g.mapPanel.GetWidget(), h2)
	setBandHeight(g.feedScroll.GetWidget(), h3)

	mw := float64(outsideW - newsTextSideInset)
	if mw < newsTextMinWidth {
		mw = newsTextMinWidth
	}
	g.newsText.MaxWidth = mw

	g.root.RequestRelayout()
	g.feedScrollNeedBottom = true
}

func (g *Game) requestFeedScrollBottom() {
	g.feedScrollTarget = 1
	extra, _, ok := g.feedScrollSlack()
	if !ok || extra <= 0 {
		return
	}
	if g.feedScrollPx < 0 {
		g.feedScrollPx = g.feedScroll.ScrollTop * extra
	}
}

// feedScrollSlack is content height minus viewport height (pixels scrollable), or ok false if widgets missing.
func (g *Game) feedScrollSlack() (extra, viewH float64, ok bool) {
	if g.feedScroll == nil || g.newsText == nil {
		return 0, 0, false
	}
	end := profileSection("update", "feed.PreferredSize")
	_, ch := g.newsText.PreferredSize()
	end()
	viewH = float64(g.feedScroll.ViewRect().Dy())
	extra = float64(ch) - viewH
	return extra, viewH, true
}

// stepSmoothFeedScroll moves feedScrollPx toward feedScrollTarget*extra and writes ScrollTop.
// Used every frame after ui.Update for both auto “scroll to bottom” and manual wheel (target-only) input.
func (g *Game) stepSmoothFeedScroll() {
	end := profileSection("update", "feed.stepSmooth")
	defer end()
	extra, _, ok := g.feedScrollSlack()
	if !ok || extra <= 0 {
		if g.feedScroll != nil {
			g.feedScroll.ScrollTop = 0
		}
		g.feedScrollPx = 0
		return
	}

	targetPx := g.feedScrollTarget * extra
	if g.feedScrollPx < 0 {
		g.feedScrollPx = g.feedScroll.ScrollTop * extra
	}
	if g.feedScrollPx > extra {
		g.feedScrollPx = extra
	}

	dt := time.Since(g.feedScrollLastSmooth).Seconds()
	g.feedScrollLastSmooth = time.Now()
	if dt <= 0 || dt > 0.2 {
		dt = 1.0 / 60.0
	}
	k := 1 - math.Exp(-feedScrollLambda*dt)
	diff := targetPx - g.feedScrollPx
	if math.Abs(diff) < 0.25 {
		g.feedScrollPx = targetPx
	} else {
		g.feedScrollPx += diff * k
	}

	g.feedScroll.ScrollTop = g.feedScrollPx / extra
	if g.feedScroll.ScrollTop < 0 {
		g.feedScroll.ScrollTop = 0
		g.feedScrollPx = 0
	}
	if g.feedScroll.ScrollTop > 1 {
		g.feedScroll.ScrollTop = 1
		g.feedScrollPx = extra
	}
}

// appendFeedLine appends a single bullet line to the news feed and schedules an
// auto-scroll to the bottom on the next frame (deferred via feedScrollNeedBottom because
// triggering PreferredSize during Layout has crashed ebitenui in the past). Silent —
// callers pick their own SFX (pushNews plays `news`, the Logos loss-email path plays
// `email` instead). Empty strings are ignored so callers don't have to guard.
func (g *Game) appendFeedLine(line string) {
	if line == "" || g.newsText == nil {
		return
	}
	g.newsText.Label += "\n\n• " + line
	if g.root != nil {
		g.root.RequestRelayout()
	}
	g.feedScrollNeedBottom = true
}

// pushNews is the standard news-feed entry point: appends the line and plays the `news`
// SFX. Used by the patch-news path and the win-sequence bulletins.
func (g *Game) pushNews(line string) {
	if line == "" {
		return
	}
	g.appendFeedLine(line)
	playSFX(sfxNewsPCM)
}

// scheduleNews queues a news line to appear in the feed after `delay`. Used by
// applyPatch so the consequence line lands a beat after the patch itself (boom +
// node lockdown), giving the player time to register the action before reading
// about the economic fallout. Empty lines are dropped (no silent placeholders).
func (g *Game) scheduleNews(line string, delay time.Duration) {
	if line == "" {
		return
	}
	g.pendingNews = append(g.pendingNews, pendingNewsItem{
		line: line,
		at:   time.Now().Add(delay),
	})
}

// flushPendingNews pushes any scheduled news whose deadline has passed. Called
// from Update each frame so patch-consequence lines appear with the scripted
// delay regardless of frame rate. Preserves order via an in-place compaction so
// a flurry of patches still surfaces consequences in the order they were queued.
func (g *Game) flushPendingNews() {
	if len(g.pendingNews) == 0 {
		return
	}
	now := time.Now()
	kept := g.pendingNews[:0]
	for _, p := range g.pendingNews {
		if !now.Before(p.at) {
			g.pushNews(p.line)
			continue
		}
		kept = append(kept, p)
	}
	g.pendingNews = kept
}

func (g *Game) Update() error {
	if g.handleTitleScreen() {
		return nil
	}
	if g.handleCredits() {
		return nil
	}
	profileMaybeBeginFrame(g)

	end := profileSection("update", "checkGameOver")
	g.checkGameOver()
	end()
	if g.handleScreenOff() {
		return nil
	}

	now := time.Now()
	dt := now.Sub(g.lastSimTick)
	g.lastSimTick = now

	if !g.gameEnded() {
		end = profileSection("update", "sim")
		if time.Since(g.lastAttackAt) >= attackInterval {
			g.lastAttackAt = time.Now()
			g.attackTick()
		}
		g.progressAttacks()
		g.accumulateInfection(dt)
		g.accumulateProduction(dt)
		g.accumulateContainment(dt)
		g.easeNodes(dt)
		end()
	} else {
		end = profileSection("update", "easeNodes")
		g.easeNodes(dt)
		end()
	}

	end = profileSection("update", "clock")
	updateClock(g.clockText)
	end()

	end = profileSection("update", "ui.Update")
	g.ui.Update()
	end()
	if g.feedScrollNeedBottom {
		g.feedScrollNeedBottom = false
		end = profileSection("update", "feed.requestBottom")
		g.requestFeedScrollBottom()
		end()
	}
	if g.handleSettingsMenu() {
		// A tap consumed by the settings UI never falls through to nodes / patch
		// menu / feed drag on the same frame, so the menu can overlap the map
		// area without opening an Attack's patch menu behind it.
		end = profileSection("update", "input")
		g.handleFeedDrag()
		g.stepSmoothFeedScroll()
		g.flushPendingNews()
		end()
		return nil
	}
	end = profileSection("update", "input")
	g.handleDebugMenu()
	g.handlePatchClick()
	g.handleFeedDrag()
	g.stepSmoothFeedScroll()
	g.flushPendingNews()
	end()
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	defer profileEndFrame()

	if g.showTitle {
		g.drawTitleScreen(screen)
		return
	}
	if g.showingCredits {
		g.drawCredits(screen)
		return
	}
	if g.end != nil && g.end.screenOff {
		g.drawScreenOff(screen)
		return
	}
	end := profileSection("draw", "ui.Draw")
	g.ui.Draw(screen)
	end()
	g.drawNodeMap(screen)
	end = profileSection("draw", "drawPatchFloats")
	g.drawPatchFloats(screen)
	end()
	end = profileSection("draw", "drawGameOverlay")
	g.drawGameOverlay(screen)
	end()
	end = profileSection("draw", "drawHint")
	g.drawHint(screen)
	end()
	end = profileSection("draw", "drawPatchMenu")
	g.drawPatchMenu(screen)
	end()
	end = profileSection("draw", "drawDebugMenu")
	g.drawDebugMenu(screen)
	end()
	end = profileSection("draw", "drawSettingsMenu")
	g.drawSettingsMenu(screen)
	end()
}

func (g *Game) Layout(_, _ int) (int, int) {
	g.applyVerticalBands(layoutWidth, layoutHeight)
	return layoutWidth, layoutHeight
}

// Run is the package's exported entry point. cmd/logos/main.go is a thin
// shim that calls Run; everything game-side lives here so the cmd binary
// stays a one-liner and the game logic stays import-friendly for tests
// and future hosts (e.g. a separate web shell).
func Run() {
	initProfiling()

	ebiten.SetWindowTitle("Zero-Day Lunch")
	ebiten.SetWindowResizingMode(ebiten.WindowResizingModeDisabled)
	ebiten.SetWindowSize(windowWidth, windowHeight)

	g, err := newGame()
	if err != nil {
		log.Fatal(err)
	}

	if err := ebiten.RunGame(g); err != nil {
		log.Fatal(err)
	}
}
